name: read-io
version: '0.0.0.1'
license: MIT
license-file: LICENSE
maintainer: firas@zaidan.de
stability: stable
github: zaidan/read-io
synopsis: Read IO library
description: >
    A lightweight library to read and write data types deriving Read and Show.
category: System
author:
  - Firas Zaidan
extra-source-files:
  - README.md

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DeriveFunctor
  - FlexibleContexts
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - ViewPatterns

dependencies:
  - base       >= 4.9 && < 5.0
  - filepath   >= 1.4 && < 1.5
  - directory  >= 1.2 && < 1.3
  - containers >= 0.5 && < 0.6


library:
  source-dirs: src
  dependencies: []

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - read-io
      - hspec
